/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    posts: Post;
    'case-studies': CaseStudy;
    plans: Plan;
    testimonials: Testimonial;
    media: Media;
    users: User;
    leads: Lead;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    plans: PlansSelect<false> | PlansSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * One or two plain sentences. Shown on cards and in search results.
   */
  excerpt: string;
  heroImage: number | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category: 'connectivity' | 'voip' | 'support' | 'business';
  author?: (number | null) | User;
  publishedAt: string;
  /**
   * Rounded reading time in minutes.
   */
  readingMinutes?: number | null;
  /**
   * Featured articles lead the blog index and the homepage strip.
   */
  featured?: boolean | null;
  /**
   * Used in the URL. Changing this breaks existing links and search rankings.
   */
  slug: string;
  seo?: {
    /**
     * Falls back to the page title. Aim for 50 to 60 characters.
     */
    title?: string | null;
    /**
     * Shown in search results. Aim for 140 to 160 characters.
     */
    description?: string | null;
    /**
     * Share card image, 1200x630. Falls back to the main image.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe what is happening in the image for screen readers. Do not start with "image of".
   */
  alt: string;
  /**
   * Optional. Only shown where a layout calls for a visible caption.
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  /**
   * Shown on articles this person authors.
   */
  jobTitle?: string | null;
  avatar?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  /**
   * The business name, exactly as they want it written.
   */
  client: string;
  /**
   * The outcome in one line. Not the client name again.
   */
  title: string;
  summary: string;
  sector: 'retail' | 'professional' | 'logistics' | 'ecommerce' | 'hospitality';
  /**
   * Town or city, province.
   */
  location: string;
  services: ('fibre' | 'wireless' | 'failover' | 'voip' | 'managed')[];
  heroImage: number | Media;
  challenge: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  approach: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  outcome: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Only publish figures the client has signed off on. Leave empty rather than estimating.
   */
  results?:
    | {
        /**
         * e.g. "4 hours"
         */
        value: string;
        /**
         * e.g. "From call to fix"
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  quote?: {
    /**
     * Keep it to three lines or fewer. Trim, do not paraphrase.
     */
    text?: string | null;
    name?: string | null;
    role?: string | null;
  };
  publishedAt: string;
  /**
   * Featured case studies appear on the homepage.
   */
  featured?: boolean | null;
  /**
   * Used in the URL. Changing this breaks existing links and search rankings.
   */
  slug: string;
  seo?: {
    /**
     * Falls back to the page title. Aim for 50 to 60 characters.
     */
    title?: string | null;
    /**
     * Shown in search results. Aim for 140 to 160 characters.
     */
    description?: string | null;
    /**
     * Share card image, 1200x630. Falls back to the main image.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Plan specifications and pricing must be confirmed with Hypernet before they go live.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans".
 */
export interface Plan {
  id: number;
  name: string;
  /**
   * Who this is sized for. e.g. "Two to five people, one location."
   */
  audience: string;
  /**
   * e.g. "Up to 50 Mbps"
   */
  downstream: string;
  voipLines: string;
  /**
   * e.g. "Business hours"
   */
  support: string;
  /**
   * Leave blank to show "Priced on your setup". Never publish a price that has not been confirmed.
   */
  price?: string | null;
  /**
   * e.g. "per month, excl. VAT"
   */
  priceNote?: string | null;
  includes?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Only one plan should carry this.
   */
  recommended?: boolean | null;
  /**
   * Low numbers sort first.
   */
  order: number;
  /**
   * Tick only once Hypernet has signed off on these figures. Unverified plans stay out of the public plan table.
   */
  verified?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * Three lines maximum on the page. Trim the original rather than running long.
   */
  quote: string;
  name: string;
  role: string;
  business: string;
  location: string;
  portrait?: (number | null) | Media;
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  business?: string | null;
  email: string;
  phone: string;
  interest:
    | 'connectivity'
    | 'voip'
    | 'both'
    | 'cloudpath'
    | 'unified-communications'
    | 'contact-centre'
    | 'secure-business'
    | 'dragon-guard'
    | 'integration-suite'
    | 'other';
  message?: string | null;
  /**
   * Which page the enquiry came from.
   */
  source?: string | null;
  status: 'new' | 'contacted' | 'quoted' | 'closed';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'plans';
        value: number | Plan;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  heroImage?: T;
  content?: T;
  category?: T;
  author?: T;
  publishedAt?: T;
  readingMinutes?: T;
  featured?: T;
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  client?: T;
  title?: T;
  summary?: T;
  sector?: T;
  location?: T;
  services?: T;
  heroImage?: T;
  challenge?: T;
  approach?: T;
  outcome?: T;
  results?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  quote?:
    | T
    | {
        text?: T;
        name?: T;
        role?: T;
      };
  publishedAt?: T;
  featured?: T;
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans_select".
 */
export interface PlansSelect<T extends boolean = true> {
  name?: T;
  audience?: T;
  downstream?: T;
  voipLines?: T;
  support?: T;
  price?: T;
  priceNote?: T;
  includes?:
    | T
    | {
        item?: T;
        id?: T;
      };
  recommended?: T;
  order?: T;
  verified?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  name?: T;
  role?: T;
  business?: T;
  location?: T;
  portrait?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  jobTitle?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  business?: T;
  email?: T;
  phone?: T;
  interest?: T;
  message?: T;
  source?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  /**
   * Short uppercase label above the headline.
   */
  badge: string;
  /**
   * First line of the headline, in Ink.
   */
  headlineLead: string;
  /**
   * Second line, set in Hypernet Blue.
   */
  headlineAccent: string;
  /**
   * Twenty words maximum. It has to fit the first screen on a laptop.
   */
  subtext: string;
  /**
   * Portrait crop. The main parallax layer.
   */
  heroImage: number | Media;
  /**
   * Square detail shot. Floats over the top left of the main image.
   */
  heroDetailA?: (number | null) | Media;
  /**
   * Square detail shot. Floats over the bottom right.
   */
  heroDetailB?: (number | null) | Media;
  heroCallout?: {
    /**
     * e.g. "Third ring"
     */
    value?: string | null;
    /**
     * e.g. "Average pickup on the support line"
     */
    label?: string | null;
  };
  sectorsHeading: string;
  sectors?:
    | {
        label: string;
        detail: string;
        id?: string | null;
      }[]
    | null;
  servicesHeading: string;
  servicesIntro: string;
  /**
   * The two pillars: connectivity and VoIP.
   */
  services?:
    | {
        title: string;
        body: string;
        points?:
          | {
              point: string;
              id?: string | null;
            }[]
          | null;
        href: string;
        linkLabel: string;
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  processHeading: string;
  processIntro: string;
  /**
   * The steps of the support process, in order.
   */
  process?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  proofHeading: string;
  proofPoints?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Tall cell in the proof grid.
   */
  proofImageA?: (number | null) | Media;
  /**
   * Wide cell in the proof grid.
   */
  proofImageB?: (number | null) | Media;
  ctaHeading: string;
  ctaBody: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  phone: string;
  /**
   * e.g. +27115551234
   */
  phoneHref: string;
  email: string;
  /**
   * Full https:// link. Optional.
   */
  whatsapp?: string | null;
  /**
   * e.g. "Mon to Fri, 07:00 to 19:00. After-hours on Priority plans."
   */
  supportHours: string;
  addressLines?:
    | {
        line: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The claim the band leads with. This is a statement of how Hypernet works, not a measurement, so it does not need sign-off.
   */
  metricsStatement: string;
  /**
   * One short supporting paragraph.
   */
  metricsSupport: string;
  metrics?:
    | {
        /**
         * e.g. "99.9%"
         */
        value: string;
        /**
         * Uppercase caption. e.g. "NETWORK UPTIME"
         */
        label: string;
        /**
         * One short clarifying line.
         */
        detail?: string | null;
        /**
         * Unverified figures are hidden from the live site. This is deliberate.
         */
        verified?: boolean | null;
        id?: string | null;
      }[]
    | null;
  trustHeading: string;
  trustIntro: string;
  accreditations?:
    | {
        /**
         * e.g. "ICASA registration"
         */
        name: string;
        /**
         * e.g. registration or membership number, once issued.
         */
        detail?: string | null;
        /**
         * Ticked entries show a confirmed badge. Unticked entries show "In progress" instead of being hidden.
         */
        verified?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * One short paragraph under the wordmark.
   */
  footerNote?: string | null;
  legalLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  badge?: T;
  headlineLead?: T;
  headlineAccent?: T;
  subtext?: T;
  heroImage?: T;
  heroDetailA?: T;
  heroDetailB?: T;
  heroCallout?:
    | T
    | {
        value?: T;
        label?: T;
      };
  sectorsHeading?: T;
  sectors?:
    | T
    | {
        label?: T;
        detail?: T;
        id?: T;
      };
  servicesHeading?: T;
  servicesIntro?: T;
  services?:
    | T
    | {
        title?: T;
        body?: T;
        points?:
          | T
          | {
              point?: T;
              id?: T;
            };
        href?: T;
        linkLabel?: T;
        image?: T;
        id?: T;
      };
  processHeading?: T;
  processIntro?: T;
  process?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  proofHeading?: T;
  proofPoints?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  proofImageA?: T;
  proofImageB?: T;
  ctaHeading?: T;
  ctaBody?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  phone?: T;
  phoneHref?: T;
  email?: T;
  whatsapp?: T;
  supportHours?: T;
  addressLines?:
    | T
    | {
        line?: T;
        id?: T;
      };
  metricsStatement?: T;
  metricsSupport?: T;
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        detail?: T;
        verified?: T;
        id?: T;
      };
  trustHeading?: T;
  trustIntro?: T;
  accreditations?:
    | T
    | {
        name?: T;
        detail?: T;
        verified?: T;
        id?: T;
      };
  footerNote?: T;
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}